import { Roles } from 'src/common/constants/enums/roles.enum';
import { SellerType } from 'src/common/constants/enums/seller-types.enum';
import { CreatePermissionDto } from 'src/permissions/dto/create-permission.dto';
import { CreateUserDto } from 'src/users/dto/create-user.dto';

export const PermissionsSeeder: CreatePermissionDto[] = [
  // BUYER permissions
  {
    role: Roles.BUYER,
    seller_type: null,
    entity: 'user',
    write: false,
    read: true,
    update: true,
    delete: false,
  },
  {
    role: Roles.BUYER,
    seller_type: null,
    entity: 'comparative_product',
    write: true,
    read: true,
    update: true,
    delete: true,
  },
  {
    role: Roles.BUYER,
    seller_type: null,
    entity: 'shopping_cart_item',
    write: true,
    read: true,
    update: true,
    delete: true,
  },
  {
    role: Roles.BUYER,
    seller_type: null,
    entity: 'product',
    write: false,
    read: true,
    update: false,
    delete: false,
  },
  {
    role: Roles.BUYER,
    seller_type: null,
    entity: 'service',
    write: false,
    read: true,
    update: false,
    delete: false,
  },
  {
    role: Roles.BUYER,
    seller_type: null,
    entity: 'order',
    write: true,
    read: true,
    update: true,
    delete: false,
  },
  {
    role: Roles.BUYER,
    seller_type: null,
    entity: 'order_item',
    write: false,
    read: true,
    update: true,
    delete: false,
  },
  {
    role: Roles.BUYER,
    seller_type: null,
    entity: 'payment',
    write: true,
    read: true,
    update: false,
    delete: false,
  },
  {
    role: Roles.BUYER,
    seller_type: null,
    entity: 'refund',
    write: true,
    read: true,
    update: false,
    delete: false,
  },
  {
    role: Roles.BUYER,
    seller_type: null,
    entity: 'seller_account',
    write: false,
    read: false,
    update: false,
    delete: false,
  },
  {
    role: Roles.BUYER,
    seller_type: null,
    entity: 'variant_product',
    write: false,
    read: true,
    update: false,
    delete: false,
  },
  {
    role: Roles.BUYER,
    seller_type: null,
    entity: 'service_schedule',
    write: false,
    read: true,
    update: false,
    delete: false,
  },
  {
    role: Roles.BUYER,
    seller_type: null,
    entity: 'service_booking',
    write: false,
    read: true,
    update: false,
    delete: false,
  },
  {
    role: Roles.BUYER,
    seller_type: null,
    entity: 'payment_seller',
    write: false,
    read: false,
    update: false,
    delete: false,
  },
  {
    role: Roles.BUYER,
    seller_type: null,
    entity: 'seller_refund',
    write: false,
    read: false,
    update: false,
    delete: false,
  },
  {
    role: Roles.BUYER,
    seller_type: null,
    entity: 'refund_history',
    write: false,
    read: false,
    update: false,
    delete: false,
  },
  {
    role: Roles.BUYER,
    seller_type: null,
    entity: 'shopping_cart',
    write: false,
    read: true,
    update: false,
    delete: false,
  },
  {
    role: Roles.BUYER,
    seller_type: null,
    entity: 'image',
    write: false,
    read: false,
    update: false,
    delete: false,
  },

  // Store Seller Permissions
  {
    role: Roles.SELLER,
    seller_type: SellerType.STORE,
    entity: 'product',
    write: true,
    read: true,
    update: true,
    delete: true,
  },
  {
    role: Roles.SELLER,
    seller_type: SellerType.STORE,
    entity: 'variant_product',
    write: true,
    read: true,
    update: true,
    delete: true,
  },
  {
    role: Roles.SELLER,
    seller_type: SellerType.STORE,
    entity: 'order_item',
    write: false,
    read: true,
    update: true,
    delete: false,
  },
  {
    role: Roles.SELLER,
    seller_type: SellerType.STORE,
    entity: 'user',
    write: false,
    read: true,
    update: true,
    delete: false,
  },
  {
    role: Roles.SELLER,
    seller_type: SellerType.STORE,
    entity: 'seller_account',
    write: true,
    read: true,
    update: true,
    delete: true,
  },
  {
    role: Roles.SELLER,
    seller_type: SellerType.STORE,
    entity: 'image',
    write: true,
    read: true,
    update: false,
    delete: true,
  },
  {
    role: Roles.SELLER,
    seller_type: SellerType.STORE,
    entity: 'seller_refund',
    write: false,
    read: true,
    update: true,
    delete: false,
  },
  {
    role: Roles.SELLER,
    seller_type: SellerType.STORE,
    entity: 'order',
    write: false,
    read: false,
    update: false,
    delete: false,
  },
  {
    role: Roles.SELLER,
    seller_type: SellerType.STORE,
    entity: 'payment_seller',
    write: false,
    read: true,
    update: false,
    delete: false,
  },
  {
    role: Roles.SELLER,
    seller_type: SellerType.STORE,
    entity: 'service',
    write: false,
    read: false,
    update: false,
    delete: false,
  },
  {
    role: Roles.SELLER,
    seller_type: SellerType.STORE,
    entity: 'service_schedule',
    write: false,
    read: false,
    update: false,
    delete: false,
  },
  {
    role: Roles.SELLER,
    seller_type: SellerType.STORE,
    entity: 'service_booking',
    write: false,
    read: false,
    update: false,
    delete: false,
  },
  {
    role: Roles.SELLER,
    seller_type: SellerType.STORE,
    entity: 'refund',
    write: false,
    read: false,
    update: false,
    delete: false,
  },
  {
    role: Roles.SELLER,
    seller_type: SellerType.STORE,
    entity: 'refund_history',
    write: false,
    read: false,
    update: false,
    delete: false,
  },
  {
    role: Roles.SELLER,
    seller_type: SellerType.STORE,
    entity: 'shopping_cart',
    write: false,
    read: false,
    update: false,
    delete: false,
  },
  {
    role: Roles.SELLER,
    seller_type: SellerType.STORE,
    entity: 'shopping_cart_item',
    write: false,
    read: false,
    update: false,
    delete: false,
  },
  {
    role: Roles.SELLER,
    seller_type: SellerType.STORE,
    entity: 'comparative_product',
    write: false,
    read: false,
    update: false,
    delete: false,
  },
  {
    role: Roles.SELLER,
    seller_type: SellerType.STORE,
    entity: 'payment',
    write: false,
    read: false,
    update: false,
    delete: false,
  },

  // Service Seller Permissions
  {
    role: Roles.SELLER,
    seller_type: SellerType.SERVICE,
    entity: 'service',
    write: true,
    read: true,
    update: true,
    delete: true,
  },
  {
    role: Roles.SELLER,
    seller_type: SellerType.SERVICE,
    entity: 'service_schedule',
    write: true,
    read: true,
    update: true,
    delete: true,
  },
  {
    role: Roles.SELLER,
    seller_type: SellerType.SERVICE,
    entity: 'service_booking',
    write: false,
    read: true,
    update: true,
    delete: false,
  },
  {
    role: Roles.SELLER,
    seller_type: SellerType.SERVICE,
    entity: 'user',
    write: false,
    read: true,
    update: true,
    delete: false,
  },
  {
    role: Roles.SELLER,
    seller_type: SellerType.SERVICE,
    entity: 'seller_account',
    write: true,
    read: true,
    update: true,
    delete: true,
  },
  {
    role: Roles.SELLER,
    seller_type: SellerType.SERVICE,
    entity: 'image',
    write: true,
    read: true,
    update: false,
    delete: true,
  },
  {
    role: Roles.SELLER,
    seller_type: SellerType.SERVICE,
    entity: 'refund',
    write: false,
    read: false,
    update: false,
    delete: false,
  },
  {
    role: Roles.SELLER,
    seller_type: SellerType.SERVICE,
    entity: 'seller_refund',
    write: false,
    read: true,
    update: true,
    delete: false,
  },
  {
    role: Roles.SELLER,
    seller_type: SellerType.SERVICE,
    entity: 'refund_history',
    write: false,
    read: false,
    update: false,
    delete: false,
  },
  {
    role: Roles.SELLER,
    seller_type: SellerType.SERVICE,
    entity: 'shopping_cart',
    write: false,
    read: false,
    update: false,
    delete: false,
  },
  {
    role: Roles.SELLER,
    seller_type: SellerType.SERVICE,
    entity: 'shopping_cart_item',
    write: false,
    read: false,
    update: false,
    delete: false,
  },
  {
    role: Roles.SELLER,
    seller_type: SellerType.SERVICE,
    entity: 'comparative_product',
    write: false,
    read: false,
    update: false,
    delete: false,
  },
  {
    role: Roles.SELLER,
    seller_type: SellerType.SERVICE,
    entity: 'payment',
    write: false,
    read: false,
    update: false,
    delete: false,
  },
  {
    role: Roles.SELLER,
    seller_type: SellerType.SERVICE,
    entity: 'order',
    write: false,
    read: false,
    update: false,
    delete: false,
  },
  {
    role: Roles.SELLER,
    seller_type: SellerType.SERVICE,
    entity: 'order_item',
    write: false,
    read: true,
    update: true,
    delete: false,
  },
  {
    role: Roles.SELLER,
    seller_type: SellerType.SERVICE,
    entity: 'product',
    write: false,
    read: false,
    update: false,
    delete: false,
  },
  {
    role: Roles.SELLER,
    seller_type: SellerType.SERVICE,
    entity: 'variant_product',
    write: false,
    read: false,
    update: false,
    delete: false,
  },
  {
    role: Roles.SELLER,
    seller_type: SellerType.SERVICE,
    entity: 'payment_seller',
    write: false,
    read: true,
    update: false,
    delete: false,
  },
];

// users seeder data----------------------------------------------------------

export const UsersSeeder: CreateUserDto[] = [
  // Store sellers
  {
    name: 'tienda uno',
    email: 'tienda1@example.com',
    password: 'Abc1234*',
    role: Roles.SELLER,
    seller_type: SellerType.STORE,
  },
  {
    name: 'tienda dos',
    email: 'tienda2@example.com',
    password: 'Abc1234*',
    role: Roles.SELLER,
    seller_type: SellerType.STORE,
  },
  {
    name: 'tienda tres',
    email: 'tienda3@example.com',
    password: 'Abc1234*',
    role: Roles.SELLER,
    seller_type: SellerType.STORE,
  },

  // Service sellers
  {
    name: 'servicio uno',
    email: 'servicio1@example.com',
    password: 'Abc1234*',
    role: Roles.SELLER,
    seller_type: SellerType.SERVICE,
  },
  {
    name: 'servicio dos',
    email: 'servicio2@example.com',
    password: 'Abc1234*',
    role: Roles.SELLER,
    seller_type: SellerType.SERVICE,
  },

  // Buyers
  {
    name: 'comprador uno',
    email: 'comprador1@example.com',
    password: 'Abc1234*',
    role: Roles.BUYER,
    seller_type: null,
  },
  {
    name: 'comprador dos',
    email: 'comprador2@example.com',
    password: 'Abc1234*',
    role: Roles.BUYER,
    seller_type: null,
  },
  {
    name: 'comprador tres',
    email: 'comprador3@example.com',
    password: 'Abc1234*',
    role: Roles.BUYER,
    seller_type: null,
  },
];
